osx_image: xcode10.1
language: swift
branches:
  only:
    - develop
    - master
before_install:
  - gem i slather --no-ri --no-rdoc
script:
  - set -o pipefail 
  - xcodebuild clean build -workspace Example/AppEventTracker.xcworkspace -scheme AppEventTracker-Example -destination 'platform=iOS Simulator,name=iPhone 7' ONLY_ACTIVE_ARCH=YES | xcpretty
  - pod lib lint
  - xcodebuild test -enableCodeCoverage YES -workspace Example/AppEventTracker.xcworkspace -scheme AppEventTracker-Example -destination 'platform=iOS Simulator,name=iPhone 7' -derivedDataPath build ONLY_ACTIVE_ARCH=YES | xcpretty
after_success:
  - slather coverage -x --output-directory reports --scheme AppEventTracker-Example --binary-basename AppEventTracker --build-directory build Example/AppEventTracker.xcodeproj
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode